name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Initializing virtual-machine
        uses: actions/checkout@v4

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: install dependencies
        run: pip install -r requirements.txt

      - name: Download model from Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python -c "from huggingface_hub import snapshot_download; snapshot_download(repo_id='Raghav0511/distilbert-sentiment-imdb', local_dir='models/distilbert-sentiment', token='${HF_TOKEN}')"

      - name: running tests
        run: pytest

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install huggingface_hub
        run: pip install huggingface_hub

      - name: Download model from Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python -c "from huggingface_hub import snapshot_download; snapshot_download(repo_id='Raghav0511/distilbert-sentiment-imdb', local_dir='models/distilbert-sentiment', token='${HF_TOKEN}')"

      - name: Build Docker image
        run: docker build -t sentiment-analysis:ci .

  docker-push:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/raghavagarwa010/sentiment-analysis-mlops-api:latest
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.streamlit
          push: true
          tags: ghcr.io/raghavagarwa010/sentiment-analysis-mlops-streamlit:latest